<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://dev.dcloud.org:8080
  cloud_crowd_console:  http://dev.dcloud.org:8080
  server_root:          dev.dcloud.org
  asset_root:           dev.dcloud.org
  large_file_storage:   /mnt/large_files
  aws_region:           us-east-1
  aws_zone:             us-east-1c
  preconfigured_ami_id: <%= secrets['ami'] %>
  mail_sender:          no-reply@lschreiner.de
  mail_support:         support@lschreiner.de
  mail_info:            info@lschreiner.de
  mail_no_reply:        no-reply@lschreiner.de
  mail_sender:          support@lschreiner.de
  enable_omniauth:      no

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server:  <%= secrets['db_host'] %>:8080
  cloud_crowd_console: staging.documentcloud.org:8080
  server_root:         staging.documentcloud.org
  asset_root:          s3.amazonaws.com/dcloud_staging

production:
  <<: *defaults
  cloud_crowd_server:  <%= secrets['db_host'] %>:8080
  cloud_crowd_console: db01.documentcloud.org:8080
  server_root:         www.documentcloud.org
  asset_root:          assets.documentcloud.org

test:
  <<: *defaults
